### ISSUE TITLE
Wrong documentation about Dynamic Routes?

### ISSUE THREAD

**Issue by mori5321** [uhyo/rocon#10]
Hi. Thank you for creating this awesome library. 
I'm using this on electron.  I totally love the concept of this library.

# Documentaion Mistake
BTW, I guess I found a documentation mistake around ["Dynamic Routes"](https://rocon.uhyohyo.net/tutorial/dynamic-routes).

The doc says as follows,  but  it doesn't work(at least in my environment, which is v1.2.0).
It raises type error "Expected 2 arguments but got 1"

``` sample.ts
const toplevelRoutes = Rocon.Path()
  .any("id");

const userRoutes = toplevelRoutes.anyRoute
  .attach(Rocon.Path())
  .route("profile", (route) => route.action(({ id }) =>
    <p>Your ID is {id}</p>
  ));
```

I guess it should be like this. (I confirmed it works). 
``` sample.ts
const toplevelRoutes = Rocon.Path()
  .any("id", {}); // modified here

const userRoutes = toplevelRoutes.anyRoute
  .attach(Rocon.Path())
  .route("profile", (route) => route.action(({ id }) =>
    <p>Your ID is {id}</p>
  ));
```

Besides, if you make the document contributable on Github, I'm willing to help with documtation improvement.

# Versions
rocon / 1.2.0
typescript / 4.1.3
react / 17.0.1 
electron /  11.1.1

# Screenshot
![image](https://user-images.githubusercontent.com/15435180/103845610-bfc1a480-50df-11eb-8b34-917898627dc7.png)
[![Image from Gyazo](https://i.gyazo.com/1bfba570d917327aabd638d596feda49.png)](https://gyazo.com/1bfba570d917327aabd638d596feda49)

**Comment by uhyo** [comment]
Thank you for reporting this!
Yes, the documentation should be fixed (or maybe, Rocon could be fixed so `any("id")` is valid).

By the way, the Rocon website source code is available here: https://github.com/uhyo/rocon-website
If you would not mind, I will appreciate your help on the fix.

**Comment by mori5321** [comment]
Thank you for your guide. I made a pull request.
https://github.com/uhyo/rocon/pull/11

And I am also glad to help with improving Rocon websites. I'll try it.
