### ISSUE TITLE
Is there any good idea to realize private route?

### ISSUE THREAD

**Issue by mori5321** [uhyo/rocon#18]
In react-router, we can implement 'private routes' like below.

``` router.tsx
<Router>
   <Switch>
       <Route exact path="/signin" component={SignIn} />
       <Route exact path="/signup" component={SignUp} />

       <!-- If authorization succeeds, we can render private routes. If not, redirect to SignUp -->
       <Auth> 
         <Switch>
           <Route exact path="/" component={Home} />
           <Route exact path="/profile" component={Profile} />
         </Switch>
       </Auth>
   </Switch>
</Router>
```

Now I'm trying to implement private routes by rocon.
If anyone has a good idea, plz tell me about it. 
(If I find a solution,  I'll show the way and example of cource)

**Comment by uhyo** [comment]
Sorry for not responding this. 😨 
This would need something like "middlewares" and I'm not sure if it is Rocon business.
Even though some parts of the route tree are private, we can't hide them at the type level.

Basically I'd like to check auth explicitly at the leaf (each single route), not mid-tree.

However, proposal of similar use cases are still welcome and actually I'm kind of willing to implement or accept such feature as long as it does not complicate Rocon's core business.
