### ISSUE TITLE
Need "history" for dependencies?

### ISSUE THREAD

**Issue by mtgto** [uhyo/rocon#6]
[RoconRoot](https://github.com/uhyo/rocon/blob/v1.1.1/src/react/components/RoconRoot.tsx) uses [history](https://www.npmjs.com/package/history).
But I don't install in my react project since I use rocon.
Do you think about add `history` to rocon's dependencies or write it in README?

**Comment by uhyo** [comment]
Thank you for fixing this @hikarinotomadoi !
